name: Unity Build (Personal License)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Unity Project without Manual Activation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Unity
        uses: webbertakken/unity-builder@v2.0-alpha-6  # ✅ fork版を使用
        with:
          unityVersion: 6000.0.46f1                    # ✅ 晴希くんのUnityバージョン
          targetPlatform: StandaloneWindows64         # ✅ PC用ビルド
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
