name: Unity Build (No License)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Unity Build without Manual License
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Unity
        uses: game-ci/unity-builder@main  # ✅ 最新版指定！
        with:
          unityVersion: 6000.0.46f1
          targetPlatform: StandaloneWindows64
          activateLicense: false  # ✅ 明示的に無効化
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
