name: Unity Build (Using Supported Docker Tag)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Unity (Linux Mono)
        uses: webbertakken/unity-builder@v2.0-alpha-6
        with:
          unityVersion: 2022.3.27f1
          targetPlatform: StandaloneLinux64
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
